### ISSUE TITLE
Socketcan timestamps are missing sub-second precision

### ISSUE THREAD

**Issue by stefanbie** [hardbyte/python-can#1021] opened 2021-04-21 09:35 UTC
Hi 

Im running python-can 3.3.4 with python 3.8.5. When I run the code below to listen to messages on can1...

```
bus = can.Bus(channel='can1', bustype='socketcan', bitrate='500000')
reader = can.BufferedReader()
notifier = can.Notifier(bus, [reader])
msg = reader.get_message(timeout=100)
```

... the message revived looks like this:

![msg](https://user-images.githubusercontent.com/16132067/115531758-70217600-a295-11eb-827a-a83268933952.png)

There is no "is_rx" property as stated in the documentation, how can this be achieved? 

BR Stefan

**Comment by zariiii9003** [comment] 2021-04-21 20:31
It is available on the develop branch. You could try the pre release version [here](https://github.com/hardbyte/python-can/releases/tag/4.0.0-dev.1)

**Comment by stefanbie** [comment] 2021-04-22 06:37
Thanks for your answer, very appreciated! Now I can see the Rx/Tx *property, however, timestamps seems to be in seconds by default?

**Comment by felixdivo** [comment] 2021-04-22 13:34
Timestamps are always in seconds, yes. This is normal for Python, e.g. see [`time.time`](https://docs.python.org/3/library/time.html#time.time).

**Comment by stefanbie** [comment] 2021-04-22 13:49
I believe, In 3.3.4 default timestamp precision is microseconds, at least for hw timestamp that I use. Now with dev branch I get second precision.

**Comment by felixdivo** [comment] 2021-04-22 13:55
Even in your version, the timestamp should've been in seconds. See [the docs](https://python-can.readthedocs.io/en/3.3.4/message.html#can.Message.timestamp).

**Comment by stefanbie** [comment] 2021-04-22 14:58
With the same code as above I get following message with the dev (4.0.0.dev0) branch:

![image](https://user-images.githubusercontent.com/16132067/115736666-bd800f00-a38b-11eb-9cdb-8b3e3e9fac3e.png)

See the difference in timestamp?

**Comment by felixdivo** [comment] 2021-04-22 15:25
Oh sorry! You meant the *precision*, not the format.

I can also reproduce it with this on commit 404876533b2ec886732869b8a8756018907acae9 (currently the most recent one on `develop`)

```python
import can

with can.Bus(channel='vcan0', bustype='socketcan') as bus:
    with can.Bus(channel='vcan0', bustype='socketcan') as bus_sender:
        bus_sender.send(can.Message(arbitration_id=3))

    print(bus.recv(timeout=100))
```

**Comment by felixdivo** [comment] 2021-04-23 21:24
You can now install version `4.0.0.dev2`.

**Comment by stefanbie** [comment] 2021-04-26 06:53
Hi

I tried to use 4.0.0.dev2 (wget
https://github.com/hardbyte/python-can/archive/refs/tags/4.0.0-dev.2.tar.gz)
but it was still seconds precision.

BR Stefan

Den fre 23 apr. 2021 kl 23:24 skrev Felix Divo ***@***.***>:

**Comment by felixdivo** [comment] 2021-04-26 08:07
Yes, that's because #1029 is not merged yet and also not release. You can install from that branch to get the fix immediately. Apparently, something like this should work: `pip install https://github.com/user/repository/archive/branch.zip`.

**Closed** 2021-05-10 23:10 UTC
Labels: backend:socketcan, backend:udp_multicast, blocker, bug
