### ISSUE TITLE
Bad dlc on received messages

### ISSUE THREAD

**Issue by matisla** [hardbyte/python-can#320] opened 2018-06-05 14:09 UTC
I had error a message:
`WARNING:can.message:data link count was 12 but it should be less than or equal to 8`

I checked with CANalyzer what's happend:
![image](https://user-images.githubusercontent.com/3169375/40981092-6a53ebc4-68da-11e8-8e73-f0683d21595a.png)
But everything looks good.

after some test I see this:
`Timestamp: 1528206835.494456        ID: 03e9    S          DLC: 12    00 00 00 00 00 00 00 00`

This happend only on one message of my DBC.

How is it possible ? Where should I look to find the bug ?
I use a CANCaseXL from Vector

**Comment by felixdivo** [comment] 2018-06-05 14:20
Are you working with normal CAN or CAN-FD frames?

**Comment by matisla** [comment] 2018-06-05 14:26
Normal CAN 2.0A (11 bit arbitration ID)

**Comment by felixdivo** [comment] 2018-09-06 19:37
Well, apparently no one could help you as of now. Me neither, because I don't own a CANCaseXL. Have you been able to further locate the problem? Did you try using the C API directly?

**Comment by felixdivo** [comment] 2018-10-09 09:20
I will close this as we cannot reproduce this.

**Closed by felixdivo** 2018-10-09 09:20 UTC
Labels: question
