### ISSUE TITLE
Report "The receive queue was read too late" error

### ISSUE THREAD

**Issue by DanielTian90** [hardbyte/python-can#863] opened 2020-07-02 04:30 UTC
Hello,

I am trying to use notifier function to monitor CAN BUS, after running for a while it will show me "The receive queue was read too late" error.
HW I use is PCAN-FD, please help me to check the error, many thanks.

**Comment by karlding** [comment] 2020-07-10 08:20
This would seem to imply the Notifier isn't processing messages fast enough off the receive queue.

How are you creating the `Notifier`? Are you using the asyncio variant or the version backed by a background thread?

**Comment by felixdivo** [comment] 2021-04-23 22:43
Closing since the problem is not reproducible. @DanielTian90 please comment if the issue is still there.

**Closed by felixdivo** 2021-04-23 22:43 UTC
